export const CURRENT_HOST = 'CURRENT_HOST'

/* 
    properties
*/
export const HANDLE_DRAWER = 'HANDLE_DRAWER'
export const FETCH_ALL_PROPERTIES = 'FETCH_ALL_PROPERTIES'
export const NEW_PROPERTY = 'NEW_PROPERTY'
export const PATCH_FETCH_PROPERTY = 'PATCH_FETCH_PROPERTY'
export const SHOW_PROPERTY = 'SHOW_PROPERTY'
export const PAGE_COUNT = 'PAGE_COUNT'
export const HANDLE_PAGE_CLICK = 'HANDLE_PAGE_CLICK'
export const DELETE_PROPERTY = 'DELETE_PROPERTY'